# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: node:6
clone:
  depth: full
pipelines:
  default:
    - step:
        script:
          - git push https://heroku:ea99bf35-459d-4ffe-972c-28d317122417@git.heroku.com/firmaelectronica.git HEAD